services:
  rest-service:
    build: .
    ports:
      - "8888:8081"
    environment:
      - BASE_API_URL=http://host.docker.internal:1337/swiftsend
      - SWIFT_SEND_API_KEY=${SWIFT_SEND_API_KEY}
      - STUDENT_GROUP=${STUDENT_GROUP}
