spring.application.name=rest-service
server.port=8081
spring.config.import=optional:file:.env[.properties]

# SwiftSend Configuration
SWIFT_SEND_API_URL=${BASE_API_URL}/swiftsend
SWIFT_SEND_API_KEY=${SWIFT_SEND_API_KEY}
SWIFT_SEND_STUDENT_GROUP=${STUDENT_GROUP}

# AsyncFlow Configuration
ASYNC_FLOW_API_URL=${BASE_API_URL}/asyncflow
ASYNC_FLOW_API_KEY=${ASYNC_FLOW_API_KEY}
ASYNC_FLOW_STUDENT_GROUP=${STUDENT_GROUP}

# LegacyLink Configuration
legacylink.api.url=${BASE_API_URL}/legacylink/sendsms
legacylink.api.username=${LEGACY_LINK_USERNAME}
legacylink.api.password=${LEGACY_LINK_PASSWORD}
legacylink.api.student-group=${STUDENT_GROUP}

# SecurePost Configuration
BASE_API_URL=${BASE_API_URL}/securepost
SECURE_POST_CLIENT_ID=${SECURE_POST_CLIENT_ID}
SECURE_POST_CLIENT_SECRET=${SECURE_POST_CLIENT_SECRET}
STUDENT_GROUP=${STUDENT_GROUP}
