spring.application.name=rest-service
server.port=8081
spring.config.import=optional:file:.env[.properties]

# SwiftSend Configuration
SWIFT_SEND_API_URL=http://localhost:8080/api/swift
SWIFT_SEND_API_KEY=your-api-key
SWIFT_SEND_STUDENT_GROUP=your-group

# AsyncFlow Configuration
ASYNC_FLOW_API_URL=http://localhost:8080/api/async
ASYNC_FLOW_API_KEY=your-api-key
ASYNC_FLOW_STUDENT_GROUP=your-group
