apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: postgres
    type: postgres
    url: postgres:5432
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: 'disable'
      postgresVersion: 13
      database: $POSTGRES_DB
